apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs1
spec:
  replicas: 3
  selector:
    matchLabels:
      team: prod
    matchExpressions:
    - key: location
      operator: In
      values: 
      - "US"
  template:
    metadata:
      labels: 
        team: prod
        tier: front
        location: "US"  # Make sure this label matches the selector
    spec:
      containers:
      - name: nginx-container
        image: nginx
