apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  replicas: 4
  selector:
     team: prod
  template:
     metadata:
       name: tej2
       labels: 
         app: web
         region: US
         team: prod
     spec:
      containers:
      - name: nginx-container
        image: nginx


   