apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wpapp
  name: wpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpapp
  strategy: {}
  template:
    metadata:
      labels:
        app: wpapp
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wpapp
  name: wpapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wpapp
  type: NodePort